export const AUDIT_ACTION_LABEL: Record<string, string> = {
  MEMBER_SUSPENDED: "Membre suspendu",
  MEMBER_REACTIVATED: "Membre réactivé",
  ADMIN_CREDIT_GRANTED: "Crédit d'inscription accordé",
  SUBSCRIPTION_CREDIT_GRANTED: "Abonnement accordé (admin)",
  REWARD_DELIVERY_UPDATED: "Statut de livraison mis à jour",
  COURSE_CREATED: "Cours créé",
  COURSE_GENERATED_AI: "Cours généré par IA",
  MODULE_CREATED: "Module créé",
  MODULE_UPDATED: "Module modifié",
  LESSON_CREATED: "Leçon créée",
  LESSON_UPDATED: "Leçon modifiée",
  COURSE_STATUS_UPDATED: "Statut de cours modifié",
  QUIZ_SAVED: "Quiz enregistré",
  PARAMETER_UPDATED: "Paramètre modifié",
  COURSE_PRICING_UPDATED: "Prix/points de formation modifié",
  COURSE_THUMBNAIL_UPDATED: "Miniature de formation modifiée",
  COMMISSION_RULE_CREATED: "Règle de commission créée",
  SALE_REFUNDED: "Vente remboursée",
  WITHDRAWAL_APPROVED: "Retrait validé",
  WITHDRAWAL_REJECTED: "Retrait refusé",
};
